package org.firstinspires.ftc.teamcode.config;

/**
 * GENERATED by tools/genconstants.mjs from java/teamcode/assets/shottable.csv,
 * which tools/shottable.ts produces for the current robot. Do not edit by hand.
 *
 * 31 ranges. The solver runs on a laptop; the hub only interpolates.
 */
public final class ShotTableData {
    private ShotTableData() { }

    public static final double[] RANGE_IN = { 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78, 82, 86, 90, 94, 98, 102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150 };
    public static final double[] HOOD_POS = { 0.8333, 0.8, 0.7333, 0.7, 0.6667, 0.6333, 0.6, 0.6, 0.5667, 0.5333, 0.5, 0.4667, 0.4667, 0.3667, 0.3667, 0.3333, 0.3, 0.3, 0.2667, 0.2667, 0.2333, 0.2333, 0.2, 0.2, 0.1667, 0.1667, 0.1333, 0.1333, 0.1, 0.1, 0.1 };
    public static final double[] RPM      = { 2199, 2222, 2255, 2282, 2315, 2349, 2387, 2420, 2459, 2492, 2531, 2570, 2608, 2664, 2691, 2735, 2791, 2818, 2868, 2896, 2951, 2979, 3028, 3062, 3117, 3144, 3200, 3233, 3294, 3321, 3354 };
    public static final double[] MARGIN   = { 0.0603, 0.0597, 0.0588, 0.0557, 0.0549, 0.0541, 0.0509, 0.0502, 0.0472, 0.0466, 0.0437, 0.0452, 0.0424, 0.0456, 0.0431, 0.0424, 0.0416, 0.0392, 0.0405, 0.0382, 0.0375, 0.0353, 0.0365, 0.0361, 0.0355, 0.0334, 0.0328, 0.0325, 0.0336, 0.0316, 0.0313 };

    // What the land-probability gate needs. The hub still solves nothing: these are the
    // solver's own outputs per range, and LandProbability turns them into a number.
    public static final double[] SPEED_LO    = { 4.675, 4.725, 4.8, 4.875, 4.95, 5.025, 5.125, 5.2, 5.3, 5.375, 5.475, 5.55, 5.65, 5.75, 5.825, 5.925, 6.05, 6.125, 6.225, 6.3, 6.425, 6.5, 6.6, 6.675, 6.8, 6.875, 7, 7.075, 7.2, 7.275, 7.35 };
    public static final double[] SPEED_HI    = { 5.275, 5.325, 5.4, 5.45, 5.525, 5.6, 5.675, 5.75, 5.825, 5.9, 5.975, 6.075, 6.15, 6.3, 6.35, 6.45, 6.575, 6.625, 6.75, 6.8, 6.925, 6.975, 7.1, 7.175, 7.3, 7.35, 7.475, 7.55, 7.7, 7.75, 7.825 };
    public static final double[] SIGMA_SPEED = { 0.07462, 0.07537, 0.0765, 0.07744, 0.07856, 0.07969, 0.081, 0.08307, 0.08344, 0.08548, 0.08587, 0.08808, 0.0885, 0.09124, 0.09216, 0.09365, 0.10184, 0.09884, 0.10429, 0.10138, 0.10692, 0.10411, 0.10938, 0.11044, 0.1122, 0.11309, 0.11952, 0.12055, 0.12804, 0.12328, 0.12431 };
    public static final double[] P_STAY      = { 0.862, 0.862, 0.862, 0.8773, 0.9079, 0.9385, 0.9474, 0.9563, 0.9622, 0.9651, 0.9681, 0.9809, 0.9936, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
    /** Half-width of the mouth across the shot line, m, less the ball radius. */
    public static final double[] HALF_LAT_M  = { 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121, 0.2121 };

    // MEASURED score -> frequency mapping from config/landcal.json (tools/landcal.ts).
    // Without it the threshold is a score with a percent sign on it.
    public static final double[] CAL_SCORE    = { 0.397806, 0.506242, 0.516873, 0.533798, 0.558037, 0.572976, 0.591209, 0.683693, 0.750630, 0.810600 };
    public static final double[] CAL_OBSERVED = { 0.839506, 0.839506, 0.839506, 0.839506, 0.839506, 0.839506, 0.864198, 0.950617, 1.000000, 1.000000 };
    /** The best frequency any bin of shots actually achieved. No threshold above this can be met. */
    public static final double CAL_CEILING = 1.000000;
}
